name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Unit tests
      run: cargo test --verbose
    - name: General interpretation tests
      run: cargo run -- --debug examples/test.runk
    - name: Fibonacci test
      run: cargo run examples/fibonacci/fibonacci.runk < examples/fibonacci/input.txt | diff examples/fibonacci/output.txt -
    - name: Factorial test
      run: cargo run examples/factorial/factorial.runk < examples/factorial/input.txt | diff examples/factorial/output.txt -
